### ISSUE TITLE
correct compat level

### ISSUE THREAD

**Issue by FeignInt** [FeignInt/dosbox-staging-deb#3]
Relates to #2
currently set with `debhelper-compat (=11)` in build-depends
This is very noisy on Debian sid ( aka unstable, bullseye/sid )

:information_source: level 11 was required for Ubuntu Bionic.

Builds by Xenial, Trusty and  Precise fail as level 11 is too high.
- To clarify, installation of build-depends fails.

**TODO**
- [x] ~~Drop~~ amend build-depend and/or fall back to compat file
   - That should also silence a `Lintian` warning on Bionic.
- [x] Adjust compat according to codename target.

---
**For consideration**
- [x] drop older ubuntu versions from the `supported distros` list returned by  https://api.launchpad.net.
- Since the list is ordered newest»oldest , and Bionic is the oldest that currently builds, break after bionic completes.
-
